### ISSUE TITLE
IndexOutOfRangeException on some video files

### ISSUE THREAD

**Issue by LesKent** [ptr727/PlexCleaner#235]
### Is this a new issue that can be reproduced?

- [X] This is a new issue that can be reproduced.

### Which operating systems reproduce the issue?

- [X] Windows
- [ ] Docker
- [ ] Other

### Version information.

2.6.100+0961577e62.0961577e626ca0a9fd1826caf31b3a19c80fff23

### Steps to reproduce?

I run Plexcleaner as a scheduled job on a tree of movie content that is being constantatly added to. I'm seeing an increasing number of files that fail with this same error that stops the entire process. I have been deleting the specific media that causes the issue so I can get past it and I manually force a download of a different media file that does not have a problem but the number is files failing seems to be increasing. 

### Commandline.

```Text
PlexCleaner.exe --settingsfile "PlexCleaner.json" --logfile "PlexCleaner.log" process --mediafiles "D:\Movies"
```

### Relevant log output.

```Text
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PlexCleaner.BitrateInfo.Calculate(List`1 packetList, Int32 videoStream, Int32 audioStream, Int32 threshold) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/BitrateInfo.cs:line 0
   at PlexCleaner.ProcessFile.GetBitrateInfo(BitrateInfo& bitrateInfo) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/ProcessFile.cs:line 1408
   at PlexCleaner.ProcessFile.VerifyBitrate() in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/ProcessFile.cs:line 1051
   at PlexCleaner.ProcessFile.Verify(Boolean& modified) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/ProcessFile.cs:line 805
   at PlexCleaner.Process.ProcessFile(FileInfo fileInfo, Boolean& modified, States& state, FileInfo& processInfo) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 409
   at PlexCleaner.Process.<>c__DisplayClass5_0.<ProcessFiles>b__0(FileInfo fileInfo) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 162
   at PlexCleaner.Process.ProcessFilesDriver(List`1 fileList, String taskName, Func`2 taskFunc) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 650
   at PlexCleaner.Process.ProcessFiles(List`1 fileList) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 134
   at PlexCleaner.Program.ProcessCommand(CommandLineOptions options) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Program.cs:line 114
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Settings file.

{
  "SchemaVersion": 2,
  "ToolsOptions": {
    "UseSystem": false,
    "RootPath": ".\\Tools\\",
    "RootRelative": true,
    "AutoUpdate": false
  },
  "ConvertOptions": {
    "EnableH265Encoder": true,
    "VideoEncodeQuality": 22,
    "AudioEncodeCodec": "ac3"
  },
  "ProcessOptions": {
    "DeleteEmptyFolders": true,
    "DeleteUnwantedExtensions": true,
    "KeepExtensions": [
      ".partial~",
      ".nfo",
      ".jpg",
      ".png", 
      ".srt",
      ".smi",
      ".ssa",
      ".ass",
      ".bif", 
      ".vtt"
    ],
    "ReMux": true,
    "ReMuxExtensions": [
      ".avi",
      ".m2ts",
      ".ts",
      ".vob",
      ".mp4",
      ".m4v",
      ".asf",
      ".wmv"
    ],
    "DeInterlace": false,
    "ReEncode": true,
    "ReEncodeVideo": [
      {
        "Format": "mpeg2video"
      },
      {
        "Format": "vc1"
      },
      {
        "Format": "wmv3"
      },
      {
        "Format": "msrle"
      },
      {
        "Format": "rawvideo"
      },
      {
        "Format": "indeo5"
      },
      {
        "Format": "h264",
        "Profile": "Constrained Baseline@30"
      },
      {
        "Format": "mpeg4",
        "Codec": "dx50"
      },
      {
        "Format": "msmpeg4v2",
        "Codec": "mp42"
      },
      {
        "Format": "msmpeg4v3",
        "Codec": "div3"
      }
    ],
    "ReEncodeAudioFormats": [
      "flac",
      "mp2",
      "vorbis",
      "wmapro",
      "opus",
      "wmav2",
      "adpcm_ms",
      "pcm_u8",
      "pcm_s16le"
    ],
    "SetUnknownLanguage": false,
    "DefaultLanguage": "eng",
    "RemoveUnwantedLanguageTracks": true,
    "KeepLanguages": [
      "eng",
      "por", 
      "spa", 
      "fra", 
      "fre", 
      "ger", 
      "deu", 
      "ita", 
      "chi"
    ],
    "RemoveDuplicateTracks": false,
    "PreferredAudioFormats": [
      "truehd atmos",
      "truehd",
      "dts-hd master audio",
      "dts-hd high resolution audio",
      "dts",
      "e-ac-3",
      "ac-3"
    ],
    "RemoveTags": true,
    "UseSidecarFiles": true,
    "SidecarUpdateOnToolChange": true,
    "Verify": true,
    "RestoreFileTimestamp": false,
    "FileIgnoreList": []
  },
  "MonitorOptions": {
    "MonitorWaitTime": 60,
    "FileRetryWaitTime": 5,
    "FileRetryCount": 2
  },
  "VerifyOptions": {
    "AutoRepair": true,
    "DeleteInvalidFiles": true,
    "RegisterInvalidFiles": true,
    "MinimumDuration": 60,
    "VerifyDuration": 30,
    "IdetDuration": 0,
    "MaximumBitrate": 100000000,
    "MinimumFileAge": 0
  }
}

### Log file.

2023-10-02 14:01:03.830 -07:00 [INF] "Process" (44.50 %) : "D:\Movies\Mob Land (2023)\backdrop.jpg"
2023-10-02 14:01:03.830 -07:00 [WRN] Skipping keep extensions file : "D:\Movies\Mob Land (2023)\backdrop.jpg"
2023-10-02 14:01:03.831 -07:00 [INF] "Process" (44.50 %) : "D:\Movies\Mob Land (2023)\folder.jpg"
2023-10-02 14:01:03.831 -07:00 [WRN] Skipping keep extensions file : "D:\Movies\Mob Land (2023)\folder.jpg"
2023-10-02 14:01:03.832 -07:00 [INF] "Process" (44.50 %) : "D:\Movies\Mob Land (2023)\logo.png"
2023-10-02 14:01:03.832 -07:00 [WRN] Skipping keep extensions file : "D:\Movies\Mob Land (2023)\logo.png"
2023-10-02 14:01:03.833 -07:00 [INF] "Process" (44.50 %) : "D:\Movies\Mob Land (2023)\Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].mkv"
2023-10-02 14:01:03.866 -07:00 [INF] Reading media info from tools : "Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].mkv"
2023-10-02 14:01:03.867 -07:00 [INF] Executing MediaInfo : "--Output=XML \"D:\Movies\Mob Land (2023)\Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].mkv\""
2023-10-02 14:01:04.651 -07:00 [INF] Executing MkvMerge : "--identify \"D:\Movies\Mob Land (2023)\Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].mkv\" --identification-format json"
2023-10-02 14:01:04.795 -07:00 [INF] Executing FfProbe : "-loglevel quiet -show_streams -show_format -print_format json \"D:\Movies\Mob Land (2023)\Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].mkv\""
2023-10-02 14:01:04.910 -07:00 [INF] "MediaInfo" : Type: "VideoInfo", Format: "HEVC", HDR: "", Codec: "V_MPEGH/ISO/HEVC", Language: "zxx", Id: 1, Number: 0, Title: "GalaxyRG265 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, Profile: "Main 10@4", Interlaced: False, ClosedCaptions: False, State: None, HasErrors: False, HasTags: True
2023-10-02 14:01:04.912 -07:00 [INF] "MediaInfo" : Type: "AudioInfo", Format: "E-AC-3", Codec: "A_EAC3", Language: "eng", Id: 2, Number: 1, Title: "GalaxyRG265 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, State: None, HasErrors: False, HasTags: True
2023-10-02 14:01:04.914 -07:00 [INF] "MediaInfo" : Type: "SubtitleInfo", Format: "PGS", Codec: "S_HDMV/PGS", Language: "eng", Id: 3, Number: 2, Title: "GalaxyRG256 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, Forced: False, State: None, HasErrors: False, HasTags: True
2023-10-02 14:01:04.915 -07:00 [INF] "MediaInfo" : Type: "SubtitleInfo", Format: "PGS", Codec: "S_HDMV/PGS", Language: "spa", Id: 4, Number: 3, Title: "", Default: False, Forced: False, State: None, HasErrors: False, HasTags: False
2023-10-02 14:01:04.916 -07:00 [INF] "MkvMerge" : Type: "VideoInfo", Format: "HEVC/H.265/MPEG-H", HDR: "", Codec: "V_MPEGH/ISO/HEVC", Language: "zxx", Id: 0, Number: 1, Title: "GalaxyRG265 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, Profile: "", Interlaced: False, ClosedCaptions: False, State: None, HasErrors: False, HasTags: True
2023-10-02 14:01:04.918 -07:00 [INF] "MkvMerge" : Type: "AudioInfo", Format: "E-AC-3", Codec: "A_EAC3", Language: "eng", Id: 1, Number: 2, Title: "GalaxyRG265 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, State: None, HasErrors: False, HasTags: True
2023-10-02 14:01:04.919 -07:00 [INF] "MkvMerge" : Type: "SubtitleInfo", Format: "HDMV PGS", Codec: "S_HDMV/PGS", Language: "eng", Id: 2, Number: 3, Title: "GalaxyRG256 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, Forced: False, State: None, HasErrors: False, HasTags: True
2023-10-02 14:01:04.921 -07:00 [INF] "MkvMerge" : Type: "SubtitleInfo", Format: "HDMV PGS", Codec: "S_HDMV/PGS", Language: "spa", Id: 3, Number: 4, Title: "", Default: False, Forced: False, State: None, HasErrors: False, HasTags: False
2023-10-02 14:01:04.922 -07:00 [INF] "FfProbe" : Type: "VideoInfo", Format: "hevc", HDR: "", Codec: "H.265 / HEVC (High Efficiency Video Coding)", Language: "zxx", Id: 0, Number: 0, Title: "GalaxyRG265 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, Profile: "Main 10@120", Interlaced: False, ClosedCaptions: False, State: None, HasErrors: False, HasTags: True
2023-10-02 14:01:04.923 -07:00 [INF] "FfProbe" : Type: "AudioInfo", Format: "eac3", Codec: "ATSC A/52B (AC-3, E-AC-3)", Language: "eng", Id: 1, Number: 1, Title: "GalaxyRG265 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, State: None, HasErrors: False, HasTags: True
2023-10-02 14:01:04.924 -07:00 [INF] "FfProbe" : Type: "SubtitleInfo", Format: "hdmv_pgs_subtitle", Codec: "HDMV Presentation Graphic Stream subtitles", Language: "eng", Id: 2, Number: 2, Title: "GalaxyRG256 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, Forced: False, State: None, HasErrors: False, HasTags: True
2023-10-02 14:01:04.925 -07:00 [INF] "FfProbe" : Type: "SubtitleInfo", Format: "hdmv_pgs_subtitle", Codec: "HDMV Presentation Graphic Stream subtitles", Language: "spa", Id: 3, Number: 3, Title: "", Default: False, Forced: False, State: None, HasErrors: False, HasTags: False
2023-10-02 14:01:04.930 -07:00 [INF] Sidecar created : State: None : "Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].PlexCleaner"
2023-10-02 14:01:04.930 -07:00 [INF] Finding Closed Captions in video stream : "Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].mkv"
2023-10-02 14:01:04.931 -07:00 [INF] Executing FfProbe : "-hide_banner \"D:\Movies\Mob Land (2023)\Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].mkv\""
2023-10-02 14:01:04.981 -07:00 [INF] Calculating bitrate info : "Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].mkv"
2023-10-02 14:01:04.981 -07:00 [INF] Executing FfProbe : "-loglevel error  -show_packets -show_entries packet=codec_type,stream_index,pts_time,dts_time,duration_time,size -print_format json \"D:\Movies\Mob Land (2023)\Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].mkv\""

### Media file information.

```Text
D:\PlexCleaner>PlexCleaner.exe getmediainfo --settingsfile "PlexCleaner.json" --logfile "PlexCleaner.log" --mediafiles "D:\Movies\Mob Land (2023)\Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].mkv"
[14:54:55 INF] Loading settings from : "PlexCleaner.json"
[14:54:57 INF] Logging output to : "PlexCleaner.log"
[14:54:57 INF] Application Version : "2.6.100+0961577e62.0961577e626ca0a9fd1826caf31b3a19c80fff23", Runtime Version : "6.0.3"
[14:54:57 INF] Executing FfMpeg : "-version"
[14:54:59 INF] FfMpeg : Version: "5.1.2", Path: "D:\\PlexCleaner\\Tools\\FfMpeg\\bin\\ffmpeg.exe"
[14:54:59 INF] Executing FfProbe : "-version"
[14:55:01 INF] FfProbe : Version: "5.1.2", Path: "D:\\PlexCleaner\\Tools\\FfMpeg\\bin\\ffprobe.exe"
[14:55:01 INF] Executing MkvMerge : "--version"
[14:55:03 INF] MkvMerge : Version: "71.1.0", Path: "D:\\PlexCleaner\\Tools\\MkvToolNix\\mkvmerge.exe"
[14:55:03 INF] Executing MkvPropEdit : "--version"
[14:55:03 INF] MkvPropEdit : Version: "71.1.0", Path: "D:\\PlexCleaner\\Tools\\MkvToolNix\\mkvpropedit.exe"
[14:55:03 INF] Executing MkvExtract : "--version"
[14:55:04 INF] MkvExtract : Version: "71.1.0", Path: "D:\\PlexCleaner\\Tools\\MkvToolNix\\mkvextract.exe"
[14:55:04 INF] Executing MediaInfo : "--version"
[14:55:04 INF] MediaInfo : Version: "22.09", Path: "D:\\PlexCleaner\\Tools\\MediaInfo\\mediainfo.exe"
[14:55:04 INF] Executing HandBrake : "--version"
[14:55:05] Compile-time hardening features are enabled
Cannot load nvEncodeAPI64.dll
Cannot load nvEncodeAPI64.dll
Cannot load nvEncodeAPI64.dll
Cannot load nvEncodeAPI64.dll
[14:55:05] hb_init: starting libhb thread
[14:55:05] thread 1 started ("libhb")
HandBrake has exited.
[14:55:05 INF] HandBrake : Version: "1.5.1", Path: "D:\\PlexCleaner\\Tools\\HandBrake\\HandBrakeCLI.exe"
[14:55:05 INF] Executing SevenZip : ""
[14:55:05 INF] SevenZip : Version: "19.00", Path: "D:\\PlexCleaner\\Tools\\SevenZip\\x64\\7za.exe"
[14:55:05 INF] Creating file and folder list ...
[14:55:05 INF] Discovered 0 directories and 1 files
[14:55:05 INF] Starting "Get Media Information", processing 1 files ...
[14:55:05 INF] "Get Media Information" (100.00 %) : "D:\\Movies\\Mob Land (2023)\\Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].mkv"
[14:55:06 INF] Reading media info from sidecar : "Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].PlexCleaner"
[14:55:08 INF] Sidecar read : State: None : "Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].PlexCleaner"
[14:55:08 INF] "D:\\Movies\\Mob Land (2023)\\Mob Land (2023) - [BLURAY-1080P][EAC3 5.1][X265][imdbid=tt20424130].mkv"
[14:55:08 INF] "FfProbe" : Type: "VideoInfo", Format: "hevc", HDR: "", Codec: "H.265 / HEVC (High Efficiency Video Coding)", Language: "zxx", Id: 0, Number: 0, Title: "GalaxyRG265 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, Profile: "Main 10@120", Interlaced: False, ClosedCaptions: False, State: None, HasErrors: False, HasTags: True
[14:55:08 INF] "FfProbe" : Type: "AudioInfo", Format: "eac3", Codec: "ATSC A/52B (AC-3, E-AC-3)", Language: "eng", Id: 1, Number: 1, Title: "GalaxyRG265 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, State: None, HasErrors: False, HasTags: True
[14:55:08 INF] "FfProbe" : Type: "SubtitleInfo", Format: "hdmv_pgs_subtitle", Codec: "HDMV Presentation Graphic Stream subtitles", Language: "eng", Id: 2, Number: 2, Title: "GalaxyRG256 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, Forced: False, State: None, HasErrors: False, HasTags: True
[14:55:08 INF] "FfProbe" : Type: "SubtitleInfo", Format: "hdmv_pgs_subtitle", Codec: "HDMV Presentation Graphic Stream subtitles", Language: "spa", Id: 3, Number: 3, Title: "", Default: False, Forced: False, State: None, HasErrors: False, HasTags: False
[14:55:08 INF] "MkvMerge" : Type: "VideoInfo", Format: "HEVC/H.265/MPEG-H", HDR: "", Codec: "V_MPEGH/ISO/HEVC", Language: "zxx", Id: 0, Number: 1, Title: "GalaxyRG265 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, Profile: "", Interlaced: False, ClosedCaptions: False, State: None, HasErrors: False, HasTags: True
[14:55:08 INF] "MkvMerge" : Type: "AudioInfo", Format: "E-AC-3", Codec: "A_EAC3", Language: "eng", Id: 1, Number: 2, Title: "GalaxyRG265 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, State: None, HasErrors: False, HasTags: True
[14:55:08 INF] "MkvMerge" : Type: "SubtitleInfo", Format: "HDMV PGS", Codec: "S_HDMV/PGS", Language: "eng", Id: 2, Number: 3, Title: "GalaxyRG256 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, Forced: False, State: None, HasErrors: False, HasTags: True
[14:55:08 INF] "MkvMerge" : Type: "SubtitleInfo", Format: "HDMV PGS", Codec: "S_HDMV/PGS", Language: "spa", Id: 3, Number: 4, Title: "", Default: False, Forced: False, State: None, HasErrors: False, HasTags: False
[14:55:08 INF] "MediaInfo" : Type: "VideoInfo", Format: "HEVC", HDR: "", Codec: "V_MPEGH/ISO/HEVC", Language: "zxx", Id: 1, Number: 0, Title: "GalaxyRG265 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, Profile: "Main 10@4", Interlaced: False, ClosedCaptions: False, State: None, HasErrors: False, HasTags: True
[14:55:08 INF] "MediaInfo" : Type: "AudioInfo", Format: "E-AC-3", Codec: "A_EAC3", Language: "eng", Id: 2, Number: 1, Title: "GalaxyRG265 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, State: None, HasErrors: False, HasTags: True
[14:55:08 INF] "MediaInfo" : Type: "SubtitleInfo", Format: "PGS", Codec: "S_HDMV/PGS", Language: "eng", Id: 3, Number: 2, Title: "GalaxyRG256 - Mob.Land.2023.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265", Default: True, Forced: False, State: None, HasErrors: False, HasTags: True
[14:55:08 INF] "MediaInfo" : Type: "SubtitleInfo", Format: "PGS", Codec: "S_HDMV/PGS", Language: "spa", Id: 4, Number: 3, Title: "", Default: False, Forced: False, State: None, HasErrors: False, HasTags: False
[14:55:08 INF] Completed "Get Media Information"
[14:55:08 INF] Processing time : 00:00:02.2489204
[14:55:08 INF] Total files : 1
[14:55:08 INF] Error files : 0
```

**Comment by ptr727** [comment]
Similar issue has been fixed several versions ago, please update to the latest version, if you can repro using current version I'll take a more detailed look.

**Comment by LesKent** [comment]
I'm sorry but I had thought that PlexCleaner auto-updated and I just now noticed that I'm running a much older version than current. I'm now upgrading to the latest 3.3.2 to see if I still see this issue.

**Comment by ptr727** [comment]
Closing, please open a new issue if the current version has the same problem.
